name: Build and Push
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: docker
    container: docker.io/docker:dind
    steps:
      - name: Chekout
        uses: actions/checkout@v4
      - name: Push
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker build -t ${{ secrets.DOCKERHUB_USER }}/apprise:latest .
          docker push ${{ secrets.DOCKERHUB_TOKEN }}/apprise

